-- Test procedure for REGEXP_REPLACE
-- Run all tests for REGEXP_REPLACE

DELIMITER //
CREATE PROCEDURE TEST_REGEXP_REPLACE()
BEGIN
   CALL TEST_BY_ASSERT_TABLE('REGEXP_REPLACE', '');
END//
DELIMITER ;